-- H2 test database schema
-- H2는 Oracle 호환 모드로 실행 (jdbc:h2:mem:testdb;MODE=Oracle)

-- 1. AUTH_USERS 테이블
CREATE TABLE AUTH_USERS (
    USER_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255),
    FULL_NAME VARCHAR2(255),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    ACCOUNT_NON_LOCKED NUMBER(1) DEFAULT 1,
    CREDENTIALS_NON_EXPIRED NUMBER(1) DEFAULT 1,
    ENABLED NUMBER(1) DEFAULT 1,
    FAILED_LOGIN_ATTEMPTS NUMBER(10) DEFAULT 0,
    LAST_LOGIN_AT TIMESTAMP,
    LAST_LOGIN_IP VARCHAR2(50),
    LOCKED_AT TIMESTAMP,
    PASSWORD_CHANGED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXTERNAL_USER_ID VARCHAR2(255),
    EXTERNAL_SYSTEM VARCHAR2(50),
    PRIMARY KEY (USER_ID)
);

CREATE INDEX IDX_AUTH_USERS_TENANT ON AUTH_USERS(TENANT_ID);
CREATE UNIQUE INDEX UQ_AUTH_USERS_USERNAME ON AUTH_USERS(TENANT_ID, USERNAME);

-- 2. AUTH_ROLES 테이블
CREATE TABLE AUTH_ROLES (
    ROLE_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    DISPLAY_NAME VARCHAR2(255),
    DESCRIPTION VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_ID)
);

CREATE UNIQUE INDEX UQ_AUTH_ROLES_NAME ON AUTH_ROLES(TENANT_ID, ROLE_NAME);

-- 3. AUTH_USER_ROLES 테이블
CREATE TABLE AUTH_USER_ROLES (
    USER_ROLE_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    ROLE_ID NUMBER(19) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ROLE_ID)
);

CREATE INDEX IDX_AUTH_USER_ROLES_USER ON AUTH_USER_ROLES(USER_ID);
CREATE INDEX IDX_AUTH_USER_ROLES_ROLE ON AUTH_USER_ROLES(ROLE_ID);

-- 4. TENANT_SSO_CONFIG 테이블
CREATE TABLE TENANT_SSO_CONFIG (
    CONFIG_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    SSO_TYPE VARCHAR2(20) DEFAULT 'INTERNAL',
    SSO_ENABLED NUMBER(1) DEFAULT 0,
    RELAY_ENDPOINT VARCHAR2(500),
    RELAY_TIMEOUT_MS NUMBER(10) DEFAULT 5000,
    SSO_SERVER_URL VARCHAR2(500),
    SSO_REALM VARCHAR2(100),
    SSO_CLIENT_ID VARCHAR2(100),
    USER_SYNC_ENABLED NUMBER(1) DEFAULT 0,
    ROLE_MAPPING_ENABLED NUMBER(1) DEFAULT 0,
    ADDITIONAL_CONFIG CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CONFIG_ID)
);

CREATE UNIQUE INDEX UQ_TENANT_SSO_CONFIG ON TENANT_SSO_CONFIG(TENANT_ID);

-- 5. EXTERNAL_USER_MAPPING 테이블
CREATE TABLE EXTERNAL_USER_MAPPING (
    MAPPING_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    EXTERNAL_USER_ID VARCHAR2(255) NOT NULL,
    EXTERNAL_SYSTEM VARCHAR2(50) NOT NULL,
    LAST_SYNCED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MAPPING_ID)
);

CREATE INDEX IDX_EXT_USER_MAP_USER ON EXTERNAL_USER_MAPPING(USER_ID);
CREATE UNIQUE INDEX UQ_EXT_USER_MAP ON EXTERNAL_USER_MAPPING(TENANT_ID, EXTERNAL_USER_ID, EXTERNAL_SYSTEM);

-- 6. REFRESH_TOKENS 테이블
CREATE TABLE REFRESH_TOKENS (
    TOKEN_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    TOKEN_VALUE VARCHAR2(500) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TOKEN_ID)
);

CREATE INDEX IDX_REFRESH_TOKENS_USER ON REFRESH_TOKENS(USER_ID);
CREATE UNIQUE INDEX UQ_REFRESH_TOKENS_VALUE ON REFRESH_TOKENS(TOKEN_VALUE);

-- 7. AUTH_PERMISSIONS 테이블
CREATE TABLE AUTH_PERMISSIONS (
    PERMISSION_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    PERMISSION_CODE VARCHAR2(100) NOT NULL,
    PERMISSION_NAME VARCHAR2(255),
    RESOURCE VARCHAR2(100),
    ACTION VARCHAR2(50),
    DESCRIPTION VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PERMISSION_ID)
);

CREATE UNIQUE INDEX UQ_AUTH_PERMISSIONS ON AUTH_PERMISSIONS(TENANT_ID, PERMISSION_CODE);

-- 8. AUTH_ROLE_PERMISSIONS 테이블
CREATE TABLE AUTH_ROLE_PERMISSIONS (
    ROLE_PERMISSION_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    ROLE_ID NUMBER(19) NOT NULL,
    PERMISSION_ID NUMBER(19) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_PERMISSION_ID)
);

CREATE INDEX IDX_AUTH_ROLE_PERM_ROLE ON AUTH_ROLE_PERMISSIONS(ROLE_ID);
CREATE INDEX IDX_AUTH_ROLE_PERM_PERM ON AUTH_ROLE_PERMISSIONS(PERMISSION_ID);

-- Sequence 생성
CREATE SEQUENCE SEQ_AUTH_USERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AUTH_ROLES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AUTH_USER_ROLES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TENANT_SSO_CONFIG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EXTERNAL_USER_MAPPING START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REFRESH_TOKENS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AUTH_PERMISSIONS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AUTH_ROLE_PERMISSIONS START WITH 1 INCREMENT BY 1;
