-- H2 test database schema
-- H2는 Oracle 호환 모드로 실행 (jdbc:h2:mem:testdb;MODE=Oracle)

-- 1. AUTH_USERS 테이블
CREATE TABLE IF NOT EXISTS AUTH_USERS (
    USER_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255),
    FULL_NAME VARCHAR2(255),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    ACCOUNT_NON_LOCKED NUMBER(1) DEFAULT 1,
    CREDENTIALS_NON_EXPIRED NUMBER(1) DEFAULT 1,
    ENABLED NUMBER(1) DEFAULT 1,
    FAILED_LOGIN_ATTEMPTS NUMBER(10) DEFAULT 0,
    LAST_LOGIN_AT TIMESTAMP,
    LAST_LOGIN_IP VARCHAR2(50),
    LOCKED_AT TIMESTAMP,
    PASSWORD_CHANGED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXTERNAL_USER_ID VARCHAR2(255),
    EXTERNAL_SYSTEM VARCHAR2(50),
    PRIMARY KEY (USER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_AUTH_USERS_TENANT ON AUTH_USERS(TENANT_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_AUTH_USERS_USERNAME ON AUTH_USERS(TENANT_ID, USERNAME);

-- 2. AUTH_ROLES 테이블
CREATE TABLE IF NOT EXISTS AUTH_ROLES (
    ROLE_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    DISPLAY_NAME VARCHAR2(255),
    DESCRIPTION VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_AUTH_ROLES_NAME ON AUTH_ROLES(TENANT_ID, ROLE_NAME);

-- 3. AUTH_USER_ROLES 테이블
CREATE TABLE IF NOT EXISTS AUTH_USER_ROLES (
    USER_ROLE_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    ROLE_ID NUMBER(19) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ROLE_ID)
);

CREATE INDEX IF NOT EXISTS IDX_AUTH_USER_ROLES_USER ON AUTH_USER_ROLES(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_AUTH_USER_ROLES_ROLE ON AUTH_USER_ROLES(ROLE_ID);

-- 4. ATH_TENANT_SSO_CONFIG 테이블
CREATE TABLE IF NOT EXISTS ATH_TENANT_SSO_CONFIG (
    CONFIG_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    SSO_TYPE VARCHAR2(20) DEFAULT 'INTERNAL',
    SSO_ENABLED NUMBER(1) DEFAULT 0,
    SSO_SERVER_URL VARCHAR2(500),
    SSO_CLIENT_ID VARCHAR2(100),
    SSO_CLIENT_SECRET VARCHAR2(255),
    SSO_REALM VARCHAR2(100),
    JWT_SECRET_KEY VARCHAR2(500),
    JWT_AGENT_ID VARCHAR2(100),
    JWT_EXPIRATION_SECONDS NUMBER(10),
    CAS_VALIDATE_ENDPOINT VARCHAR2(255),
    CAS_SERVICE_URL VARCHAR2(500),
    REST_TOKEN_ENDPOINT VARCHAR2(255),
    REST_CONNECT_ENDPOINT VARCHAR2(255),
    REST_CREATE_STATE VARCHAR2(50),
    REST_VERIFY_STATE VARCHAR2(50),
    HTTP_FORM_CONFIRM_ENDPOINT VARCHAR2(255),
    HTTP_FORM_ID_PARAM VARCHAR2(50),
    HTTP_FORM_PASSWORD_PARAM VARCHAR2(50),
    HTTP_FORM_ENCODE_PASSWORD NUMBER(1) DEFAULT 1,
    LOGIN_ENDPOINT VARCHAR2(255),
    LOGOUT_ENDPOINT VARCHAR2(255),
    READ_TIMEOUT_MS NUMBER(10) DEFAULT 5000,
    USER_SYNC_ENABLED NUMBER(1) DEFAULT 0,
    ROLE_MAPPING_ENABLED NUMBER(1) DEFAULT 0,
    ADDITIONAL_CONFIG CLOB,
    RELAY_ENDPOINT VARCHAR2(500),
    RELAY_TIMEOUT_MS NUMBER(10) DEFAULT 5000,
    FALLBACK_ENABLED NUMBER(1) DEFAULT 0,
    FALLBACK_PASSWORD_REQUIRED NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CONFIG_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_ATH_TENANT_SSO_CONFIG ON ATH_TENANT_SSO_CONFIG(TENANT_ID);

-- 5. EXTERNAL_USER_MAPPING 테이블
CREATE TABLE IF NOT EXISTS EXTERNAL_USER_MAPPING (
    MAPPING_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    EXTERNAL_USER_ID VARCHAR2(255) NOT NULL,
    EXTERNAL_SYSTEM VARCHAR2(50) NOT NULL,
    LAST_SYNCED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MAPPING_ID)
);

CREATE INDEX IF NOT EXISTS IDX_EXT_USER_MAP_USER ON EXTERNAL_USER_MAPPING(USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_EXT_USER_MAP ON EXTERNAL_USER_MAPPING(TENANT_ID, EXTERNAL_USER_ID, EXTERNAL_SYSTEM);

-- 6. REFRESH_TOKENS 테이블
CREATE TABLE IF NOT EXISTS REFRESH_TOKENS (
    TOKEN_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    TOKEN_VALUE VARCHAR2(500) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TOKEN_ID)
);

CREATE INDEX IF NOT EXISTS IDX_REFRESH_TOKENS_USER ON REFRESH_TOKENS(USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_REFRESH_TOKENS_VALUE ON REFRESH_TOKENS(TOKEN_VALUE);

-- 7. AUTH_PERMISSIONS 테이블
CREATE TABLE IF NOT EXISTS AUTH_PERMISSIONS (
    PERMISSION_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    PERMISSION_CODE VARCHAR2(100) NOT NULL,
    PERMISSION_NAME VARCHAR2(255),
    RESOURCE VARCHAR2(100),
    ACTION VARCHAR2(50),
    DESCRIPTION VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PERMISSION_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_AUTH_PERMISSIONS ON AUTH_PERMISSIONS(TENANT_ID, PERMISSION_CODE);

-- 8. AUTH_ROLE_PERMISSIONS 테이블
CREATE TABLE IF NOT EXISTS AUTH_ROLE_PERMISSIONS (
    ROLE_PERMISSION_ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    ROLE_ID NUMBER(19) NOT NULL,
    PERMISSION_ID NUMBER(19) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_PERMISSION_ID)
);

CREATE INDEX IF NOT EXISTS IDX_AUTH_ROLE_PERM_ROLE ON AUTH_ROLE_PERMISSIONS(ROLE_ID);
CREATE INDEX IF NOT EXISTS IDX_AUTH_ROLE_PERM_PERM ON AUTH_ROLE_PERMISSIONS(PERMISSION_ID);

-- 9. ATH_TENANT 테이블
CREATE TABLE IF NOT EXISTS ATH_TENANT (
    ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    SITE_NAME VARCHAR2(255) NOT NULL,
    SITE_CODE VARCHAR2(50) NOT NULL,
    PRIMARY_DOMAIN VARCHAR2(255),
    ADDITIONAL_DOMAINS CLOB,
    DESCRIPTION VARCHAR2(1000),
    SITE_TITLE VARCHAR2(255),
    SITE_DESCRIPTION VARCHAR2(1000),
    THEME_NAME VARCHAR2(100),
    DEFAULT_LANGUAGE VARCHAR2(10),
    TIMEZONE VARCHAR2(50),
    OWNER_EMAIL VARCHAR2(255),
    ADMIN_EMAIL VARCHAR2(255),
    CONTACT_PHONE VARCHAR2(50),
    PARENT_TENANT_ID VARCHAR2(50),
    SITE_LEVEL NUMBER(10) DEFAULT 0,
    MAX_CONTENT_ITEMS NUMBER(19),
    MAX_STORAGE_MB NUMBER(19),
    MAX_USERS NUMBER(19),
    FEATURES CLOB,
    SETTINGS CLOB,
    STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    PUBLISHED_AT TIMESTAMP,
    UNPUBLISHED_AT TIMESTAMP,
    SUBSCRIPTION_PLAN_CODE VARCHAR2(50),
    PLAN_START_DATE TIMESTAMP,
    PLAN_END_DATE TIMESTAMP,
    VERSION NUMBER(19) DEFAULT 1,
    CREATED_BY VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(100),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_ATH_TENANT_ID ON ATH_TENANT(TENANT_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_ATH_TENANT_CODE ON ATH_TENANT(SITE_CODE);

-- 10. ATH_ROLE_STATUS 테이블
CREATE TABLE IF NOT EXISTS ATH_ROLE_STATUS (
    ID NUMBER(19) NOT NULL,
    STATUS_CODE VARCHAR2(50) NOT NULL,
    STATUS_NAME VARCHAR2(100) NOT NULL,
    ROLE_CATEGORY VARCHAR2(50),
    IS_ACTIVE CHAR(1) DEFAULT '1',
    DESCRIPTION VARCHAR2(500),
    SORT_ORDER NUMBER(10) DEFAULT 0,
    IS_DEFAULT CHAR(1) DEFAULT '0',
    CREATED_BY VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(100),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_ATH_ROLE_STATUS ON ATH_ROLE_STATUS(STATUS_CODE);

-- 11. ATH_ORGANIZATION 테이블
CREATE TABLE IF NOT EXISTS ATH_ORGANIZATION (
    ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    ORGANIZATION_ID VARCHAR2(50) NOT NULL,
    ORGANIZATION_CODE VARCHAR2(50),
    ORGANIZATION_NAME VARCHAR2(255) NOT NULL,
    ORGANIZATION_TYPE VARCHAR2(50),
    PARENT_ORGANIZATION_ID VARCHAR2(50),
    ORG_LEVEL NUMBER(10) DEFAULT 0,
    DISPLAY_ORDER NUMBER(10) DEFAULT 0,
    DESCRIPTION VARCHAR2(1000),
    ACTIVE CHAR(1) DEFAULT '1',
    CREATED_BY VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(100),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_ATH_ORG_ID ON ATH_ORGANIZATION(ORGANIZATION_ID);
CREATE INDEX IF NOT EXISTS IDX_ATH_ORG_TENANT ON ATH_ORGANIZATION(TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_ATH_ORG_PARENT ON ATH_ORGANIZATION(PARENT_ORGANIZATION_ID);

-- 12. ATH_USER_ORGANIZATION 테이블
CREATE TABLE IF NOT EXISTS ATH_USER_ORGANIZATION (
    ID NUMBER(19) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    ORGANIZATION_ID VARCHAR2(50) NOT NULL,
    ROLE_ID VARCHAR2(50),
    IS_PRIMARY CHAR(1) DEFAULT '0',
    POSITION VARCHAR2(100),
    START_DATE DATE,
    END_DATE DATE,
    ACTIVE CHAR(1) DEFAULT '1',
    CREATED_BY VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(100),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_ATH_USER_ORG_USER ON ATH_USER_ORGANIZATION(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_ATH_USER_ORG_ORG ON ATH_USER_ORGANIZATION(ORGANIZATION_ID);
CREATE INDEX IF NOT EXISTS IDX_ATH_USER_ORG_TENANT ON ATH_USER_ORGANIZATION(TENANT_ID);

-- 13. AUTH_USER_PROFILES 테이블 (사용자 프로필 - SSO 추가 데이터)
CREATE TABLE IF NOT EXISTS AUTH_USER_PROFILES (
    USER_ID VARCHAR2(50) NOT NULL,
    TENANT_ID VARCHAR2(50) NOT NULL,
    PROFILE_DATA CLOB DEFAULT '{}',
    SOURCE VARCHAR2(20) DEFAULT 'MANUAL',
    SOURCE_SYSTEM VARCHAR2(50),
    SYNCED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, TENANT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_AUTH_USER_PROFILES_TENANT ON AUTH_USER_PROFILES(TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_AUTH_USER_PROFILES_SOURCE ON AUTH_USER_PROFILES(SOURCE);

-- Sequence 생성
CREATE SEQUENCE IF NOT EXISTS SEQ_AUTH_USERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_AUTH_ROLES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_AUTH_USER_ROLES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_TENANT_SSO_CONFIG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_EXTERNAL_USER_MAPPING START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_REFRESH_TOKENS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_AUTH_PERMISSIONS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_AUTH_ROLE_PERMISSIONS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ATH_TENANT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ATH_ROLE_STATUS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ATH_ORGANIZATION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ATH_USER_ORGANIZATION START WITH 1 INCREMENT BY 1;
