-- LOTECS Auth Service - Table Creation (ATH_ prefix)
-- Source: SEJONG_DEV CMS User Tables
-- Execute as: lotecs_auth user

-- ============================================
-- 1. ATH_TENANT (테넌트)
-- ============================================
CREATE TABLE ATH_TENANT (
    TENANT_ID              VARCHAR2(50)           NOT NULL PRIMARY KEY,
    SITE_NAME              VARCHAR2(200)          NOT NULL,
    SITE_CODE              VARCHAR2(50)           NOT NULL UNIQUE,
    PRIMARY_DOMAIN         VARCHAR2(200)          UNIQUE,
    ADDITIONAL_DOMAINS     VARCHAR2(1000),
    DESCRIPTION            VARCHAR2(500),
    SITE_TITLE             VARCHAR2(200),
    SITE_DESCRIPTION       VARCHAR2(1000),
    THEME_NAME             VARCHAR2(100),
    DEFAULT_LANGUAGE       VARCHAR2(10)  DEFAULT 'ko',
    TIMEZONE               VARCHAR2(50)  DEFAULT 'Asia/Seoul',
    OWNER_EMAIL            VARCHAR2(200),
    ADMIN_EMAIL            VARCHAR2(200),
    CONTACT_PHONE          VARCHAR2(50),
    PARENT_TENANT_ID       VARCHAR2(50)           CONSTRAINT FK_ATH_TENANT_PARENT REFERENCES ATH_TENANT,
    SITE_LEVEL             NUMBER        DEFAULT 0 CONSTRAINT CK_ATH_SITE_LEVEL CHECK (site_level >= 0 AND site_level <= 5),
    MAX_CONTENT_ITEMS      NUMBER,
    MAX_STORAGE_MB         NUMBER,
    MAX_USERS              NUMBER        DEFAULT 100,
    FEATURES               VARCHAR2(4000),
    SETTINGS               VARCHAR2(4000),
    STATUS                 VARCHAR2(20)  DEFAULT 'DRAFT' CONSTRAINT CK_ATH_TENANT_STATUS CHECK (status IN ('DRAFT', 'PUBLISHED', 'SUSPENDED', 'ARCHIVED')),
    PUBLISHED_AT           TIMESTAMP(6),
    UNPUBLISHED_AT         TIMESTAMP(6),
    SUBSCRIPTION_PLAN_CODE VARCHAR2(100),
    PLAN_START_DATE        TIMESTAMP(6),
    PLAN_END_DATE          TIMESTAMP(6),
    CREATED_BY             VARCHAR2(100),
    CREATED_AT             TIMESTAMP(6)  DEFAULT SYSTIMESTAMP,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_AT             TIMESTAMP(6),
    DELETED_AT             TIMESTAMP(6),
    VERSION                NUMBER(19)    DEFAULT 0 NOT NULL
)
/

COMMENT ON TABLE ATH_TENANT IS '테넌트 관리 테이블'
/
COMMENT ON COLUMN ATH_TENANT.TENANT_ID IS '테넌트 고유 식별자'
/
COMMENT ON COLUMN ATH_TENANT.SITE_CODE IS '사이트 코드 (URL slug)'
/
COMMENT ON COLUMN ATH_TENANT.SITE_TITLE IS '사이트 제목'
/
COMMENT ON COLUMN ATH_TENANT.SITE_DESCRIPTION IS '사이트 설명'
/
COMMENT ON COLUMN ATH_TENANT.THEME_NAME IS '테마 이름'
/
COMMENT ON COLUMN ATH_TENANT.MAX_CONTENT_ITEMS IS '최대 컨텐츠 수'
/
COMMENT ON COLUMN ATH_TENANT.MAX_STORAGE_MB IS '최대 저장용량 (MB)'
/
COMMENT ON COLUMN ATH_TENANT.FEATURES IS '기능 설정 (JSON)'
/
COMMENT ON COLUMN ATH_TENANT.STATUS IS '상태: DRAFT, PUBLISHED, SUSPENDED, ARCHIVED'
/
COMMENT ON COLUMN ATH_TENANT.PUBLISHED_AT IS '게시 일시'
/
COMMENT ON COLUMN ATH_TENANT.UNPUBLISHED_AT IS '게시 중단 일시'
/
COMMENT ON COLUMN ATH_TENANT.SUBSCRIPTION_PLAN_CODE IS '구독 플랜 코드'
/
COMMENT ON COLUMN ATH_TENANT.PLAN_START_DATE IS '플랜 시작일'
/
COMMENT ON COLUMN ATH_TENANT.PLAN_END_DATE IS '플랜 종료일'
/

CREATE INDEX IDX_ATH_TENANT_STATUS ON ATH_TENANT (STATUS)
/
CREATE INDEX IDX_ATH_TENANT_PARENT ON ATH_TENANT (PARENT_TENANT_ID)
/

-- ============================================
-- 2. ATH_USERS (사용자)
-- ============================================
CREATE TABLE ATH_USERS (
    USER_ID                 VARCHAR2(36)                  NOT NULL PRIMARY KEY,
    TENANT_ID               VARCHAR2(50)                  NOT NULL,
    USERNAME                VARCHAR2(100)                 NOT NULL,
    PASSWORD                VARCHAR2(255)                 NOT NULL,
    EMAIL                   VARCHAR2(255)                 NOT NULL,
    PHONE_NUMBER            VARCHAR2(20),
    FULL_NAME               VARCHAR2(100),
    STATUS                  VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL
        CONSTRAINT CK_ATH_USERS_STATUS CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'SUSPENDED')),
    ACCOUNT_NON_LOCKED      NUMBER(1)     DEFAULT 1       NOT NULL,
    CREDENTIALS_NON_EXPIRED NUMBER(1)     DEFAULT 1       NOT NULL,
    ENABLED                 NUMBER(1)     DEFAULT 1       NOT NULL,
    LAST_LOGIN_AT           TIMESTAMP(6),
    LAST_LOGIN_IP           VARCHAR2(45),
    FAILED_LOGIN_ATTEMPTS   NUMBER(3)     DEFAULT 0
        CONSTRAINT CK_ATH_USERS_FAILED_ATTEMPTS CHECK (failed_login_attempts >= 0 AND failed_login_attempts <= 10),
    LOCKED_AT               TIMESTAMP(6),
    PASSWORD_CHANGED_AT     TIMESTAMP(6),
    CREATED_BY              VARCHAR2(36),
    CREATED_AT              TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY              VARCHAR2(36),
    UPDATED_AT              TIMESTAMP(6),
    DELETED_AT              TIMESTAMP(6),
    CONSTRAINT UK_ATH_USERS_TENANT_EMAIL    UNIQUE (TENANT_ID, EMAIL),
    CONSTRAINT UK_ATH_USERS_TENANT_USERNAME UNIQUE (TENANT_ID, USERNAME)
)
/

COMMENT ON TABLE ATH_USERS IS '사용자 계정 테이블 - 멀티테넌트 기반 인증'
/
COMMENT ON COLUMN ATH_USERS.USER_ID IS '사용자 고유 식별자 (UUID)'
/
COMMENT ON COLUMN ATH_USERS.TENANT_ID IS '테넌트 ID - 사이트별 격리'
/
COMMENT ON COLUMN ATH_USERS.USERNAME IS '사용자명 (로그인 ID) - 테넌트 내 유니크'
/
COMMENT ON COLUMN ATH_USERS.PASSWORD IS 'BCrypt 해시된 비밀번호 (work factor 12)'
/
COMMENT ON COLUMN ATH_USERS.STATUS IS '계정 상태: ACTIVE, INACTIVE, LOCKED, SUSPENDED'
/
COMMENT ON COLUMN ATH_USERS.ACCOUNT_NON_LOCKED IS '계정 잠김 여부: 1=정상, 0=잠김'
/
COMMENT ON COLUMN ATH_USERS.FAILED_LOGIN_ATTEMPTS IS '연속 로그인 실패 횟수 (5회 초과 시 계정 잠김)'
/
COMMENT ON COLUMN ATH_USERS.PASSWORD_CHANGED_AT IS '비밀번호 변경 시각 (90일 경과 시 만료)'
/
COMMENT ON COLUMN ATH_USERS.DELETED_AT IS 'Soft Delete 시각'
/

CREATE INDEX IDX_ATH_USERS_TENANT     ON ATH_USERS (TENANT_ID)
/
CREATE INDEX IDX_ATH_USERS_USERNAME   ON ATH_USERS (USERNAME)
/
CREATE INDEX IDX_ATH_USERS_EMAIL      ON ATH_USERS (EMAIL)
/
CREATE INDEX IDX_ATH_USERS_STATUS     ON ATH_USERS (STATUS)
/
CREATE INDEX IDX_ATH_USERS_DELETED_AT ON ATH_USERS (DELETED_AT)
/

-- ============================================
-- 3. ATH_ROLE_STATUS (역할 상태 마스터)
-- ============================================
CREATE TABLE ATH_ROLE_STATUS (
    STATUS_CODE   VARCHAR2(50)           NOT NULL PRIMARY KEY,
    STATUS_NAME   VARCHAR2(100)          NOT NULL,
    ROLE_CATEGORY VARCHAR2(50)           NOT NULL
        CONSTRAINT CK_ATH_ROLE_STATUS_CATEGORY CHECK (role_category IN ('STUDENT', 'PROFESSOR', 'STAFF', 'COMMON')),
    IS_ACTIVE     NUMBER(1)     DEFAULT 1 NOT NULL
        CONSTRAINT CK_ATH_ROLE_STATUS_ACTIVE CHECK (is_active IN (0, 1)),
    DESCRIPTION   VARCHAR2(500),
    SORT_ORDER    NUMBER(3)     DEFAULT 0,
    IS_DEFAULT    NUMBER(1)     DEFAULT 0
        CONSTRAINT CK_ATH_ROLE_STATUS_DEFAULT CHECK (is_default IN (0, 1)),
    CREATED_BY    VARCHAR2(36),
    CREATED_AT    TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY    VARCHAR2(36),
    UPDATED_AT    TIMESTAMP(6),
    DELETED_AT    TIMESTAMP(6)
)
/

COMMENT ON TABLE ATH_ROLE_STATUS IS '역할 상태 마스터 테이블'
/
COMMENT ON COLUMN ATH_ROLE_STATUS.STATUS_CODE IS '상태 코드: ENROLLED, ON_LEAVE, PROFESSOR_ACTIVE 등'
/
COMMENT ON COLUMN ATH_ROLE_STATUS.STATUS_NAME IS '상태 명칭: 재학, 휴학, 재직 등'
/
COMMENT ON COLUMN ATH_ROLE_STATUS.ROLE_CATEGORY IS '역할 카테고리: STUDENT, PROFESSOR, STAFF, COMMON'
/
COMMENT ON COLUMN ATH_ROLE_STATUS.IS_ACTIVE IS '활성 여부: 1=활성(권한 부여), 0=비활성(권한 차단)'
/
COMMENT ON COLUMN ATH_ROLE_STATUS.IS_DEFAULT IS '기본 상태 여부: 1=기본 상태'
/

CREATE INDEX IDX_ATH_ROLE_STATUS_CATEGORY   ON ATH_ROLE_STATUS (ROLE_CATEGORY)
/
CREATE INDEX IDX_ATH_ROLE_STATUS_ACTIVE     ON ATH_ROLE_STATUS (IS_ACTIVE)
/
CREATE INDEX IDX_ATH_ROLE_STATUS_SORT       ON ATH_ROLE_STATUS (SORT_ORDER)
/
CREATE INDEX IDX_ATH_ROLE_STATUS_DELETED_AT ON ATH_ROLE_STATUS (DELETED_AT)
/

-- ============================================
-- 4. ATH_ROLES (역할)
-- ============================================
CREATE TABLE ATH_ROLES (
    ROLE_ID      VARCHAR2(36)  NOT NULL PRIMARY KEY,
    TENANT_ID    VARCHAR2(50)  NOT NULL,
    ROLE_NAME    VARCHAR2(50)  NOT NULL,
    DISPLAY_NAME VARCHAR2(100),
    DESCRIPTION  VARCHAR2(500),
    PRIORITY     NUMBER(3)     NOT NULL,
    CREATED_BY   VARCHAR2(36),
    CREATED_AT   TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY   VARCHAR2(36),
    UPDATED_AT   TIMESTAMP(6),
    DELETED_AT   TIMESTAMP(6),
    CONSTRAINT UK_ATH_ROLES_TENANT_NAME UNIQUE (TENANT_ID, ROLE_NAME)
)
/

COMMENT ON TABLE ATH_ROLES IS '역할 테이블 - RBAC 기반 역할 관리'
/
COMMENT ON COLUMN ATH_ROLES.ROLE_ID IS '역할 고유 식별자 (UUID)'
/
COMMENT ON COLUMN ATH_ROLES.TENANT_ID IS '테넌트 ID'
/
COMMENT ON COLUMN ATH_ROLES.ROLE_NAME IS '역할 이름: STUDENT, PROFESSOR, STAFF, ADMIN'
/
COMMENT ON COLUMN ATH_ROLES.DISPLAY_NAME IS '표시용 이름: 학생, 교수, 직원, 관리자'
/
COMMENT ON COLUMN ATH_ROLES.PRIORITY IS '역할 우선순위 - 숫자가 낮을수록 높은 권한'
/
COMMENT ON COLUMN ATH_ROLES.DELETED_AT IS 'Soft Delete 시각'
/

CREATE INDEX IDX_ATH_ROLES_TENANT     ON ATH_ROLES (TENANT_ID)
/
CREATE INDEX IDX_ATH_ROLES_PRIORITY   ON ATH_ROLES (PRIORITY)
/
CREATE INDEX IDX_ATH_ROLES_DELETED_AT ON ATH_ROLES (DELETED_AT)
/

-- ============================================
-- 5. ATH_PERMISSIONS (권한)
-- ============================================
CREATE TABLE ATH_PERMISSIONS (
    PERMISSION_ID   VARCHAR2(36)   NOT NULL PRIMARY KEY,
    TENANT_ID       VARCHAR2(50)   NOT NULL,
    PERMISSION_NAME VARCHAR2(100)  NOT NULL,
    RESOURCE        VARCHAR2(50)   NOT NULL,
    ACTION          VARCHAR2(50)   NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    CREATED_BY      VARCHAR2(36),
    CREATED_AT      TIMESTAMP(6)   DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      VARCHAR2(36),
    UPDATED_AT      TIMESTAMP(6),
    DELETED_AT      TIMESTAMP(6),
    CONSTRAINT UK_ATH_PERMISSIONS_RESOURCE_ACTION UNIQUE (TENANT_ID, RESOURCE, ACTION),
    CONSTRAINT UK_ATH_PERMISSIONS_TENANT_NAME     UNIQUE (TENANT_ID, PERMISSION_NAME)
)
/

COMMENT ON TABLE ATH_PERMISSIONS IS '권한 테이블 - RBAC 기반 리소스 접근 제어'
/
COMMENT ON COLUMN ATH_PERMISSIONS.PERMISSION_ID IS '권한 고유 식별자 (UUID)'
/
COMMENT ON COLUMN ATH_PERMISSIONS.TENANT_ID IS '테넌트 ID'
/
COMMENT ON COLUMN ATH_PERMISSIONS.PERMISSION_NAME IS '권한 이름: CONTENT_WRITE, USER_MANAGE'
/
COMMENT ON COLUMN ATH_PERMISSIONS.RESOURCE IS '리소스: CONTENT, USER, MENU, TENANT'
/
COMMENT ON COLUMN ATH_PERMISSIONS.ACTION IS '액션: READ, WRITE, DELETE, MANAGE'
/
COMMENT ON COLUMN ATH_PERMISSIONS.DELETED_AT IS 'Soft Delete 시각'
/

CREATE INDEX IDX_ATH_PERMISSIONS_TENANT     ON ATH_PERMISSIONS (TENANT_ID)
/
CREATE INDEX IDX_ATH_PERMISSIONS_RESOURCE   ON ATH_PERMISSIONS (RESOURCE)
/
CREATE INDEX IDX_ATH_PERMISSIONS_DELETED_AT ON ATH_PERMISSIONS (DELETED_AT)
/

-- ============================================
-- 6. ATH_USER_ROLES (사용자-역할 매핑)
-- ============================================
CREATE TABLE ATH_USER_ROLES (
    USER_ID           VARCHAR2(36)                  NOT NULL
        CONSTRAINT FK_ATH_USER_ROLES_USER REFERENCES ATH_USERS,
    ROLE_ID           VARCHAR2(36)                  NOT NULL
        CONSTRAINT FK_ATH_USER_ROLES_ROLE REFERENCES ATH_ROLES,
    TENANT_ID         VARCHAR2(50)                  NOT NULL,
    STATUS_CODE       VARCHAR2(50)  DEFAULT 'ACTIVE' NOT NULL
        CONSTRAINT FK_ATH_USER_ROLES_STATUS REFERENCES ATH_ROLE_STATUS,
    STATUS_CHANGED_AT TIMESTAMP(6),
    STATUS_CHANGED_BY VARCHAR2(36),
    STATUS_REASON     VARCHAR2(1000),
    VALID_FROM        TIMESTAMP(6),
    VALID_UNTIL       TIMESTAMP(6),
    ASSIGNED_AT       TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    ASSIGNED_BY       VARCHAR2(36),
    REVOKED_AT        TIMESTAMP(6),
    REVOKED_BY        VARCHAR2(36),
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT CK_ATH_USER_ROLES_VALID_PERIOD CHECK (valid_from IS NULL OR valid_until IS NULL OR valid_from < valid_until)
)
/

COMMENT ON TABLE ATH_USER_ROLES IS '사용자-역할 매핑 테이블 - 역할 상태 및 유효기간 관리'
/
COMMENT ON COLUMN ATH_USER_ROLES.USER_ID IS '사용자 ID'
/
COMMENT ON COLUMN ATH_USER_ROLES.ROLE_ID IS '역할 ID'
/
COMMENT ON COLUMN ATH_USER_ROLES.STATUS_CODE IS '역할 상태 코드: ENROLLED, ON_LEAVE 등'
/
COMMENT ON COLUMN ATH_USER_ROLES.STATUS_REASON IS '상태 변경 사유'
/
COMMENT ON COLUMN ATH_USER_ROLES.VALID_FROM IS '유효 시작일 (NULL이면 즉시 활성화)'
/
COMMENT ON COLUMN ATH_USER_ROLES.VALID_UNTIL IS '유효 종료일 (NULL이면 무제한)'
/
COMMENT ON COLUMN ATH_USER_ROLES.ASSIGNED_AT IS '역할 부여 시각'
/
COMMENT ON COLUMN ATH_USER_ROLES.REVOKED_AT IS '역할 회수 시각 (NULL이면 활성 상태)'
/

CREATE INDEX IDX_ATH_USER_ROLES_USER         ON ATH_USER_ROLES (USER_ID)
/
CREATE INDEX IDX_ATH_USER_ROLES_ROLE         ON ATH_USER_ROLES (ROLE_ID)
/
CREATE INDEX IDX_ATH_USER_ROLES_TENANT       ON ATH_USER_ROLES (TENANT_ID)
/
CREATE INDEX IDX_ATH_USER_ROLES_STATUS       ON ATH_USER_ROLES (STATUS_CODE)
/
CREATE INDEX IDX_ATH_USER_ROLES_VALID_PERIOD ON ATH_USER_ROLES (VALID_FROM, VALID_UNTIL)
/
CREATE INDEX IDX_ATH_USER_ROLES_ASSIGNED_AT  ON ATH_USER_ROLES (ASSIGNED_AT)
/

-- ============================================
-- 7. ATH_ROLE_PERMISSIONS (역할-권한 매핑)
-- ============================================
CREATE TABLE ATH_ROLE_PERMISSIONS (
    ROLE_ID       VARCHAR2(36)  NOT NULL
        CONSTRAINT FK_ATH_ROLE_PERMISSIONS_ROLE REFERENCES ATH_ROLES,
    PERMISSION_ID VARCHAR2(36)  NOT NULL
        CONSTRAINT FK_ATH_ROLE_PERMISSIONS_PERM REFERENCES ATH_PERMISSIONS,
    TENANT_ID     VARCHAR2(50)  NOT NULL,
    GRANTED_AT    TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    GRANTED_BY    VARCHAR2(36),
    PRIMARY KEY (ROLE_ID, PERMISSION_ID)
)
/

COMMENT ON TABLE ATH_ROLE_PERMISSIONS IS '역할-권한 매핑 테이블 - RBAC 구현'
/
COMMENT ON COLUMN ATH_ROLE_PERMISSIONS.ROLE_ID IS '역할 ID'
/
COMMENT ON COLUMN ATH_ROLE_PERMISSIONS.PERMISSION_ID IS '권한 ID'
/
COMMENT ON COLUMN ATH_ROLE_PERMISSIONS.TENANT_ID IS '테넌트 ID'
/
COMMENT ON COLUMN ATH_ROLE_PERMISSIONS.GRANTED_AT IS '권한 부여 시각'
/
COMMENT ON COLUMN ATH_ROLE_PERMISSIONS.GRANTED_BY IS '권한 부여자 ID'
/

CREATE INDEX IDX_ATH_ROLE_PERMISSIONS_ROLE       ON ATH_ROLE_PERMISSIONS (ROLE_ID)
/
CREATE INDEX IDX_ATH_ROLE_PERMISSIONS_PERMISSION ON ATH_ROLE_PERMISSIONS (PERMISSION_ID)
/
CREATE INDEX IDX_ATH_ROLE_PERMISSIONS_TENANT     ON ATH_ROLE_PERMISSIONS (TENANT_ID)
/
CREATE INDEX IDX_ATH_ROLE_PERMISSIONS_GRANTED_AT ON ATH_ROLE_PERMISSIONS (GRANTED_AT)
/

-- ============================================
-- 8. ATH_ORGANIZATION (조직)
-- ============================================
CREATE TABLE ATH_ORGANIZATION (
    ID                     NUMBER(19)                        NOT NULL PRIMARY KEY,
    TENANT_ID              VARCHAR2(50)                      NOT NULL
        CONSTRAINT FK_ATH_ORG_TENANT REFERENCES ATH_TENANT,
    ORGANIZATION_ID        VARCHAR2(50)                      NOT NULL
        CONSTRAINT UK_ATH_ORGANIZATION_ID UNIQUE,
    ORGANIZATION_CODE      VARCHAR2(50)                      NOT NULL,
    ORGANIZATION_NAME      VARCHAR2(200)                     NOT NULL,
    ORGANIZATION_TYPE      VARCHAR2(50)                      NOT NULL,
    PARENT_ORGANIZATION_ID VARCHAR2(50)
        CONSTRAINT FK_ATH_ORG_PARENT REFERENCES ATH_ORGANIZATION (ORGANIZATION_ID),
    ORG_LEVEL              NUMBER(10)    DEFAULT 0           NOT NULL
        CONSTRAINT CK_ATH_ORG_LEVEL CHECK (org_level >= 0),
    DISPLAY_ORDER          NUMBER(10)    DEFAULT 0           NOT NULL,
    DESCRIPTION            VARCHAR2(1000),
    ACTIVE                 CHAR(1)       DEFAULT '1'         NOT NULL
        CONSTRAINT CK_ATH_ORG_ACTIVE CHECK (active IN ('1', '0')),
    CREATED_BY             VARCHAR2(50)                      NOT NULL,
    CREATED_AT             TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(50),
    UPDATED_AT             TIMESTAMP(6),
    DELETED_AT             TIMESTAMP(6)
)
/

COMMENT ON TABLE ATH_ORGANIZATION IS '조직 마스터 테이블'
/
COMMENT ON COLUMN ATH_ORGANIZATION.ID IS '내부 ID (시퀀스)'
/
COMMENT ON COLUMN ATH_ORGANIZATION.TENANT_ID IS '테넌트 ID'
/
COMMENT ON COLUMN ATH_ORGANIZATION.ORGANIZATION_ID IS '조직 ID (비즈니스 키)'
/
COMMENT ON COLUMN ATH_ORGANIZATION.ORGANIZATION_CODE IS '조직 코드: CS, EE, ADMIN'
/
COMMENT ON COLUMN ATH_ORGANIZATION.ORGANIZATION_NAME IS '조직명: 컴퓨터공학과, 전자공학과'
/
COMMENT ON COLUMN ATH_ORGANIZATION.ORGANIZATION_TYPE IS '조직 유형: COLLEGE, MAJOR, DEPARTMENT, DIVISION, TEAM'
/
COMMENT ON COLUMN ATH_ORGANIZATION.PARENT_ORGANIZATION_ID IS '상위 조직 ID'
/
COMMENT ON COLUMN ATH_ORGANIZATION.ORG_LEVEL IS '계층 레벨 (0: 최상위)'
/
COMMENT ON COLUMN ATH_ORGANIZATION.ACTIVE IS '활성화 여부: 1/0'
/
COMMENT ON COLUMN ATH_ORGANIZATION.DELETED_AT IS 'Soft Delete 시각'
/

CREATE INDEX IDX_ATH_ORGANIZATION_TENANT_ID ON ATH_ORGANIZATION (TENANT_ID)
/
CREATE INDEX IDX_ATH_ORGANIZATION_CODE      ON ATH_ORGANIZATION (ORGANIZATION_CODE)
/
CREATE INDEX IDX_ATH_ORGANIZATION_TYPE      ON ATH_ORGANIZATION (ORGANIZATION_TYPE)
/
CREATE INDEX IDX_ATH_ORGANIZATION_PARENT    ON ATH_ORGANIZATION (PARENT_ORGANIZATION_ID)
/
CREATE INDEX IDX_ATH_ORGANIZATION_DELETED   ON ATH_ORGANIZATION (DELETED_AT)
/
CREATE UNIQUE INDEX UK_ATH_ORGANIZATION_CODE ON ATH_ORGANIZATION (TENANT_ID, ORGANIZATION_CODE, NVL2(DELETED_AT, ID, NULL))
/

CREATE SEQUENCE ATH_ORGANIZATION_SEQ START WITH 1 INCREMENT BY 1
/

-- ============================================
-- 9. ATH_USER_ORGANIZATION (사용자-조직 매핑)
-- ============================================
CREATE TABLE ATH_USER_ORGANIZATION (
    ID              NUMBER(19)                        NOT NULL PRIMARY KEY,
    TENANT_ID       VARCHAR2(50)                      NOT NULL
        CONSTRAINT FK_ATH_USER_ORG_TENANT REFERENCES ATH_TENANT,
    USER_ID         VARCHAR2(50)                      NOT NULL
        CONSTRAINT FK_ATH_USER_ORG_USER REFERENCES ATH_USERS,
    ORGANIZATION_ID VARCHAR2(50)                      NOT NULL
        CONSTRAINT FK_ATH_USER_ORG_ORG REFERENCES ATH_ORGANIZATION (ORGANIZATION_ID),
    ROLE_ID         VARCHAR2(50)
        CONSTRAINT FK_ATH_USER_ORG_ROLE REFERENCES ATH_ROLES,
    IS_PRIMARY      CHAR(1)       DEFAULT '0'         NOT NULL
        CONSTRAINT CK_ATH_USER_ORG_PRIMARY CHECK (is_primary IN ('1', '0')),
    POSITION        VARCHAR2(100),
    START_DATE      DATE,
    END_DATE        DATE,
    ACTIVE          CHAR(1)       DEFAULT '1'         NOT NULL
        CONSTRAINT CK_ATH_USER_ORG_ACTIVE CHECK (active IN ('1', '0')),
    CREATED_BY      VARCHAR2(50)                      NOT NULL,
    CREATED_AT      TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50),
    UPDATED_AT      TIMESTAMP(6),
    DELETED_AT      TIMESTAMP(6),
    CONSTRAINT CK_ATH_USER_ORG_DATES CHECK (end_date IS NULL OR end_date >= start_date)
)
/

COMMENT ON TABLE ATH_USER_ORGANIZATION IS '사용자-조직 매핑 테이블'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.ID IS '내부 ID (시퀀스)'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.TENANT_ID IS '테넌트 ID'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.USER_ID IS '사용자 ID'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.ORGANIZATION_ID IS '조직 ID'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.ROLE_ID IS '역할 ID (교수, 학생, 직원 등)'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.IS_PRIMARY IS '주 소속 여부: 1(주 소속), 0(겸임)'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.POSITION IS '직책/직위: 학과장, 팀장, 과장'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.START_DATE IS '소속 시작일'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.END_DATE IS '소속 종료일 (NULL이면 현재 소속)'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.ACTIVE IS '활성화 여부: 1/0'
/
COMMENT ON COLUMN ATH_USER_ORGANIZATION.DELETED_AT IS 'Soft Delete 시각'
/

CREATE INDEX IDX_ATH_USER_ORG_TENANT  ON ATH_USER_ORGANIZATION (TENANT_ID)
/
CREATE INDEX IDX_ATH_USER_ORG_USER    ON ATH_USER_ORGANIZATION (USER_ID)
/
CREATE INDEX IDX_ATH_USER_ORG_ORG     ON ATH_USER_ORGANIZATION (ORGANIZATION_ID)
/
CREATE INDEX IDX_ATH_USER_ORG_ROLE    ON ATH_USER_ORGANIZATION (ROLE_ID)
/
CREATE INDEX IDX_ATH_USER_ORG_DELETED ON ATH_USER_ORGANIZATION (DELETED_AT)
/
CREATE UNIQUE INDEX UK_ATH_USER_ORGANIZATION ON ATH_USER_ORGANIZATION (TENANT_ID, USER_ID, ORGANIZATION_ID, NVL2(DELETED_AT, ID, NULL))
/

CREATE SEQUENCE ATH_USER_ORGANIZATION_SEQ START WITH 1 INCREMENT BY 1
/

-- ============================================
-- 10. ATH_REFRESH_TOKENS (리프레시 토큰)
-- ============================================
CREATE TABLE ATH_REFRESH_TOKENS (
    TOKEN_ID       VARCHAR2(36)                           NOT NULL PRIMARY KEY,
    USER_ID        VARCHAR2(36)                           NOT NULL
        CONSTRAINT FK_ATH_REFRESH_TOKENS_USER REFERENCES ATH_USERS ON DELETE CASCADE,
    TENANT_ID      VARCHAR2(50)                           NOT NULL,
    TOKEN_HASH     VARCHAR2(255)                          NOT NULL
        CONSTRAINT UK_ATH_REFRESH_TOKENS_HASH UNIQUE,
    TOKEN_FAMILY   VARCHAR2(36),
    ISSUED_AT      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRES_AT     TIMESTAMP(6)                           NOT NULL,
    REVOKED_AT     TIMESTAMP(6),
    REVOKED_REASON VARCHAR2(100),
    IP_ADDRESS     VARCHAR2(45),
    USER_AGENT     VARCHAR2(500),
    DEVICE_ID      VARCHAR2(100),
    LAST_USED_AT   TIMESTAMP(6),
    USED_COUNT     NUMBER(10)    DEFAULT 0,
    CONSTRAINT CK_ATH_REFRESH_TOKENS_EXPIRES CHECK (expires_at > issued_at)
)
/

COMMENT ON TABLE ATH_REFRESH_TOKENS IS 'JWT Refresh Token 저장 및 관리'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.TOKEN_ID IS '토큰 고유 식별자 (UUID)'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.USER_ID IS '사용자 ID'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.TENANT_ID IS '테넌트 ID'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.TOKEN_HASH IS 'Refresh Token SHA-256 해시'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.TOKEN_FAMILY IS '토큰 패밀리 ID (Rotation 추적)'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.ISSUED_AT IS '토큰 발급 시각'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.EXPIRES_AT IS '토큰 만료 시각 (7~30일)'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.REVOKED_AT IS '토큰 무효화 시각'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.REVOKED_REASON IS '무효화 사유: LOGOUT, SECURITY_BREACH, EXPIRED'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.IP_ADDRESS IS '토큰 발급 시 클라이언트 IP'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.USER_AGENT IS '토큰 발급 시 User-Agent'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.DEVICE_ID IS '디바이스 식별자'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.LAST_USED_AT IS '토큰 마지막 사용 시각'
/
COMMENT ON COLUMN ATH_REFRESH_TOKENS.USED_COUNT IS '토큰 사용 횟수 (재사용 감지용)'
/

CREATE INDEX IDX_ATH_REFRESH_TOKENS_USER    ON ATH_REFRESH_TOKENS (USER_ID)
/
CREATE INDEX IDX_ATH_REFRESH_TOKENS_TENANT  ON ATH_REFRESH_TOKENS (TENANT_ID)
/
CREATE INDEX IDX_ATH_REFRESH_TOKENS_EXPIRES ON ATH_REFRESH_TOKENS (EXPIRES_AT)
/
CREATE INDEX IDX_ATH_REFRESH_TOKENS_FAMILY  ON ATH_REFRESH_TOKENS (TOKEN_FAMILY)
/
CREATE INDEX IDX_ATH_REFRESH_TOKENS_ACTIVE  ON ATH_REFRESH_TOKENS (USER_ID, EXPIRES_AT, REVOKED_AT)
/

-- ============================================
-- 11. ATH_TENANT_SSO_CONFIG (SSO 설정)
-- ============================================
CREATE TABLE ATH_TENANT_SSO_CONFIG (
    TENANT_ID           VARCHAR2(50)  NOT NULL PRIMARY KEY,
    SSO_TYPE            VARCHAR2(20)  NOT NULL
        CONSTRAINT CK_ATH_SSO_TYPE CHECK (sso_type IN ('INTERNAL', 'RELAY', 'KEYCLOAK', 'LDAP', 'EXTERNAL')),
    SSO_ENABLED         NUMBER(1)     DEFAULT 1,

    -- RELAY 타입 설정 (학교 테넌트)
    RELAY_ENDPOINT      VARCHAR2(500),
    RELAY_TIMEOUT_MS    NUMBER        DEFAULT 5000,

    -- 직접 SSO 설정 (일반 기업)
    SSO_SERVER_URL      VARCHAR2(500),
    SSO_REALM           VARCHAR2(100),
    SSO_CLIENT_ID       VARCHAR2(100),
    SSO_CLIENT_SECRET   VARCHAR2(500),

    -- 동기화 설정
    USER_SYNC_ENABLED   NUMBER(1)     DEFAULT 1,
    ROLE_MAPPING_ENABLED NUMBER(1)    DEFAULT 1,

    -- 추가 설정 (JSON)
    ADDITIONAL_CONFIG   CLOB,

    CREATED_AT          TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP(6)
)
/

COMMENT ON TABLE ATH_TENANT_SSO_CONFIG IS '테넌트별 SSO 설정'
/
COMMENT ON COLUMN ATH_TENANT_SSO_CONFIG.TENANT_ID IS '테넌트 ID'
/
COMMENT ON COLUMN ATH_TENANT_SSO_CONFIG.SSO_TYPE IS 'INTERNAL: 자체인증, RELAY: lotecs-relay위임, KEYCLOAK/LDAP/EXTERNAL: 직접SSO'
/
COMMENT ON COLUMN ATH_TENANT_SSO_CONFIG.RELAY_ENDPOINT IS 'RELAY 타입 엔드포인트'
/
COMMENT ON COLUMN ATH_TENANT_SSO_CONFIG.RELAY_TIMEOUT_MS IS 'RELAY 타임아웃 (ms)'
/
COMMENT ON COLUMN ATH_TENANT_SSO_CONFIG.USER_SYNC_ENABLED IS '사용자 동기화 활성화 여부'
/
COMMENT ON COLUMN ATH_TENANT_SSO_CONFIG.ROLE_MAPPING_ENABLED IS '역할 매핑 활성화 여부'
/

CREATE INDEX IDX_ATH_SSO_TYPE ON ATH_TENANT_SSO_CONFIG (SSO_TYPE)
/

-- ============================================
-- 12. ATH_EXTERNAL_USER_MAPPING (외부 사용자 매핑)
-- ============================================
CREATE TABLE ATH_EXTERNAL_USER_MAPPING (
    MAPPING_ID       VARCHAR2(50)  NOT NULL PRIMARY KEY,
    TENANT_ID        VARCHAR2(50)  NOT NULL,
    USER_ID          VARCHAR2(50)  NOT NULL
        CONSTRAINT FK_ATH_EXT_USER REFERENCES ATH_USERS ON DELETE CASCADE,
    EXTERNAL_USER_ID VARCHAR2(200) NOT NULL,
    EXTERNAL_SYSTEM  VARCHAR2(50)  NOT NULL,
    LAST_SYNCED_AT   TIMESTAMP(6),
    CREATED_AT       TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_ATH_EXT_MAPPING UNIQUE (TENANT_ID, EXTERNAL_USER_ID, EXTERNAL_SYSTEM)
)
/

COMMENT ON TABLE ATH_EXTERNAL_USER_MAPPING IS '외부 시스템 사용자 ID 매핑 (학번<->user_id)'
/
COMMENT ON COLUMN ATH_EXTERNAL_USER_MAPPING.MAPPING_ID IS '매핑 고유 식별자'
/
COMMENT ON COLUMN ATH_EXTERNAL_USER_MAPPING.TENANT_ID IS '테넌트 ID'
/
COMMENT ON COLUMN ATH_EXTERNAL_USER_MAPPING.USER_ID IS '사용자 ID'
/
COMMENT ON COLUMN ATH_EXTERNAL_USER_MAPPING.EXTERNAL_USER_ID IS '외부 시스템 사용자 ID (학번 등)'
/
COMMENT ON COLUMN ATH_EXTERNAL_USER_MAPPING.EXTERNAL_SYSTEM IS '외부 시스템명: SEJONG_SIS, KEYCLOAK 등'
/
COMMENT ON COLUMN ATH_EXTERNAL_USER_MAPPING.LAST_SYNCED_AT IS '마지막 동기화 시각'
/

CREATE INDEX IDX_ATH_EXT_USER     ON ATH_EXTERNAL_USER_MAPPING (USER_ID)
/
CREATE INDEX IDX_ATH_EXT_EXTERNAL ON ATH_EXTERNAL_USER_MAPPING (EXTERNAL_USER_ID)
/
CREATE INDEX IDX_ATH_EXT_TENANT   ON ATH_EXTERNAL_USER_MAPPING (TENANT_ID)
/

-- ============================================
-- Verify table creation
-- ============================================
SELECT table_name FROM user_tables WHERE table_name LIKE 'ATH_%' ORDER BY table_name
/
